language: node_js
node_js:
  - "7"
install:
  - "yarn prep"
script:
  - "yarn build"
  - "cp -r dist build/dist"
  - "cp -r saved_model_* build/"
  - "cp -r images build/images"
  - "cp index.html build/index.html"
deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master
  local_dir: "build"
